package br.com.possoler.api.api_posso_ler.site.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class BlocoPerguntasFrequentes {
    private String labelPerguntasFrequentes;
    private String label1;
    private String label2;
    private String label3;
    private String label4;
    private String label5;
    private String label6;
    private String label7;
    private String label8;
    private String label9;
    private String label10;
    private String label11;
    private String label12;
    private String label13;
    private String label14;
    private String label15;
    private String label16;
    private String label17;
    private String label18;
    private String label19;
    private String label20;
    private String label21;
    private String label22;
    private String label23;
    private String label24;
    private String label25;
    private String label26;
    private String label27;
    private String label28;
    private String label29;
    private String label30;
    private String label31;
    private String label32;
    private String label33;
    private String label34;
    private String label35;
    private String label36;
    private String label37;
    private String label38;
    private String label39;
    private String label40;
    private String label41;
    private String label42;
    private String label43;
    private String label44;
    private String label45;
    private String label46;
    private String label47;
    private String label48;
    private String label49;
    private String label50;
    private String label51;
    private String label52;
    private String label53;
    private String label54;
    private String label55;
    private String label56;
    private String label57;
    private String label58;
    private String label59;
    private String label60;
    private String label61;
    private String label62;
    private String label63;
    private String label64;
    private String label65;
    private String label66;
    private String label67;
    private String label68;
    private String label69;
    private String label70;
    private String label71;
    private String label72;
    private String label73;
    private String label74;
    private String label75;
    private String label76;
    private String label77;
    private String label78;
    private String label79;
    private String label80;
    private String label81;
    private String label82;
    private String label83;
    private String label84;
}
